import type { NavItem } from "@/types/content";

export const navigation: NavItem[] = [
  {
    title: "Getting Started",
    href: "/docs/getting-started",
    icon: "rocket",
    children: [
      { title: "Overview", href: "/docs/getting-started/overview" },
      { title: "Logging In", href: "/docs/getting-started/logging-in" },
      { title: "Interface Tour", href: "/docs/getting-started/interface-tour" },
      { title: "Course Homepage", href: "/docs/getting-started/course-homepage" },
      { title: "Navbar & Tools", href: "/docs/getting-started/navbar" },
      { title: "Using the Sandbox", href: "/docs/getting-started/sandbox" },
    ],
  },
  {
    title: "Content",
    href: "/docs/course-setup",
    icon: "folder",
    children: [
      { title: "Overview", href: "/docs/course-setup/overview" },
      { title: "Creating Modules/Units", href: "/docs/course-setup/creating-modules" },
      { title: "Uploading Files", href: "/docs/course-setup/uploading-files" },
      { title: "HTML Editor", href: "/docs/course-setup/html-editor" },
      { title: "Web Links", href: "/docs/course-setup/web-links" },
      { title: "Manage Files", href: "/docs/course-setup/manage-files" },
      { title: "Release Conditions", href: "/docs/course-setup/release-conditions" },
      { title: "Learning Paths", href: "/docs/course-setup/learning-paths" },
      { title: "Checklists", href: "/docs/course-setup/checklists" },
    ],
  },
  {
    title: "Assignments",
    href: "/docs/assignments",
    icon: "file-text",
    children: [
      { title: "Overview", href: "/docs/assignments/overview" },
      { title: "Creating Assignments", href: "/docs/assignments/creating-assignments" },
      { title: "Submission Settings", href: "/docs/assignments/submission-settings" },
      { title: "Special Access", href: "/docs/assignments/special-access" },
      { title: "Turnitin", href: "/docs/assignments/turnitin" },
      { title: "Grading Submissions", href: "/docs/assignments/grading-submissions" },
    ],
  },
  {
    title: "Quizzes",
    href: "/docs/quizzes",
    icon: "help-circle",
    children: [
      { title: "Overview", href: "/docs/quizzes/overview" },
      { title: "Creating Quizzes", href: "/docs/quizzes/creating-quizzes" },
      { title: "Question Types", href: "/docs/quizzes/question-types" },
      { title: "Question Library", href: "/docs/quizzes/question-library" },
      { title: "Quiz Settings", href: "/docs/quizzes/quiz-settings" },
      { title: "Grading Quizzes", href: "/docs/quizzes/grading-quizzes" },
      { title: "Surveys", href: "/docs/quizzes/surveys" },
    ],
  },
  {
    title: "Discussions",
    href: "/docs/discussions",
    icon: "message-square",
    children: [
      { title: "Overview", href: "/docs/discussions/overview" },
      { title: "Forums vs Topics", href: "/docs/discussions/forums-vs-topics" },
      { title: "Creating Discussions", href: "/docs/discussions/creating-discussions" },
      { title: "Moderating", href: "/docs/discussions/moderating-discussions" },
      { title: "Grading Discussions", href: "/docs/discussions/grading-discussions" },
    ],
  },
  {
    title: "Classlist",
    href: "/docs/classlist",
    icon: "users-round",
    children: [
      { title: "Overview", href: "/docs/classlist/overview" },
      { title: "Attendance", href: "/docs/classlist/attendance" },
    ],
  },
  {
    title: "Grades",
    href: "/docs/gradebook",
    icon: "bar-chart",
    children: [
      { title: "Overview", href: "/docs/gradebook/overview" },
      { title: "Setup Wizard", href: "/docs/gradebook/setup-wizard" },
      { title: "Grade Items", href: "/docs/gradebook/grade-items" },
      { title: "Entering Grades", href: "/docs/gradebook/entering-grades" },
      { title: "Final Grades", href: "/docs/gradebook/final-grades" },
    ],
  },
  {
    title: "Class Progress",
    href: "/docs/analytics",
    icon: "trending-up",
    children: [
      { title: "Overview", href: "/docs/analytics/overview" },
      { title: "Using Class Progress", href: "/docs/analytics/class-progress" },
      { title: "Content Completion", href: "/docs/analytics/content-completion" },
    ],
  },
  {
    title: "Course Admin",
    href: "/docs/course-admin",
    icon: "settings",
    children: [
      { title: "Overview", href: "/docs/course-admin/overview" },
      { title: "Copying Courses", href: "/docs/course-management/copying-courses" },
      { title: "Course Templates", href: "/docs/course-management/course-templates" },
      { title: "Backup & Restore", href: "/docs/course-management/backup-restore" },
      { title: "Awards & Badges", href: "/docs/course-admin/awards" },
      { title: "Learning Outcomes", href: "/docs/course-admin/learning-outcomes" },
    ],
  },
  {
    title: "Communication",
    href: "/docs/communication",
    icon: "mail",
    children: [
      { title: "Announcements", href: "/docs/communication/announcements" },
      { title: "Email", href: "/docs/communication/email" },
      { title: "Calendar", href: "/docs/communication/calendar" },
      { title: "Notifications", href: "/docs/communication/notifications" },
      { title: "Intelligent Agents", href: "/docs/communication/intelligent-agents" },
    ],
  },
  {
    title: "Groups",
    href: "/docs/groups",
    icon: "users",
    children: [
      { title: "Creating Groups", href: "/docs/groups/creating-groups" },
      { title: "Group Assignments", href: "/docs/groups/group-assignments" },
    ],
  },
  {
    title: "Rubrics",
    href: "/docs/rubrics",
    icon: "clipboard-list",
    children: [
      { title: "Creating Rubrics", href: "/docs/rubrics/creating-rubrics" },
      { title: "Using Rubrics", href: "/docs/rubrics/using-rubrics" },
    ],
  },
  {
    title: "Video & Multimedia",
    href: "/docs/video",
    icon: "video",
    children: [
      { title: "Recording Video", href: "/docs/video/recording-video" },
      { title: "Video Assignments", href: "/docs/video/video-assignments" },
      { title: "Virtual Classroom", href: "/docs/video/virtual-classroom" },
    ],
  },
  {
    title: "Integrations",
    href: "/docs/integrations",
    icon: "plug",
    children: [
      { title: "External Tools", href: "/docs/integrations/external-tools" },
      { title: "Zoom & Teams", href: "/docs/integrations/zoom-teams" },
      { title: "Publisher Content", href: "/docs/integrations/publisher-content" },
    ],
  },
  {
    title: "Accessibility",
    href: "/docs/accessibility",
    icon: "accessibility",
    children: [
      { title: "Making Content Accessible", href: "/docs/accessibility/making-content-accessible" },
      { title: "Accessibility Checker", href: "/docs/accessibility/accessibility-checker" },
    ],
  },
  {
    title: "Troubleshooting",
    href: "/docs/troubleshooting",
    icon: "alert-circle",
    children: [
      { title: "Common Issues", href: "/docs/troubleshooting/common-issues" },
      { title: "Browser Compatibility", href: "/docs/troubleshooting/browser-compatibility" },
      { title: "Mobile App", href: "/docs/troubleshooting/mobile-app" },
      { title: "Video Problems", href: "/docs/troubleshooting/video-problems" },
    ],
  },
];
